name       : haskell-pretty
version    : 1.1.3.5
release    : 1
source     :
    - https://hackage.haskell.org/package/pretty-1.1.3.5/pretty-1.1.3.5.tar.gz : b0009d4d7915a7951ebf8519411319d65b110c2f68da7f176ec8fd98217a6f45
license    : BSD-3-Clause
component  : programming.haskell
summary    : This package contains a pretty-printing library
description: |
    This package contains a pretty-printing library, a set of API's that provides a way to easily print out text in a consistent format of your choosing.
builddeps  :
    - haskell-cabal-install
setup      : |
    %cabal_configure
build      : |
    %cabal_build
install    : |
    %cabal_install
    %cabal_register
